# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: git push https://dev.azure.com/wessex-water/_git/Bicep%20Registry%20Modules master:master
  displayName: 'git push'
